### ISSUE TITLE
[BUG] SSR: ReferenceError: SVGStyleElement is not defined

### ISSUE THREAD

**Issue by jtammen** [TinkoffCreditSystems/ng-dompurify#39]
# 🐞 Bug report

### Description

Using the `dompurify` pipe results in `ReferenceError: SVGStyleElement is not defined` in Angular Universal environment. It works in the browser.

### Reproduction

In order to sanitize styles, I am using this in my `AppBrowserModule` as mentioned [here](https://github.com/TinkoffCreditSystems/ng-dompurify#css-sanitization):

```
{
    provide: SANITIZE_STYLE,
    useValue: ɵ_sanitizeStyle
}
```

### Expected behavior

Error should not be thrown.

### Versions

-   OS: Ubuntu 18.04.3 LTS
-   Node: v12.16.1
-   Angular: 8.2.14
-   @tinkoff/ng-dompurify: 2.1.0
-   dompurify: 2.0.8

Please let me know if you need any further information.

**Comment by MarsiBarsi** [comment]
Hi, @jtammen! Thank you for your report. We will fix it soon

**Comment by MarsiBarsi** [comment]
Hi, @jtammen 

The problem has been fixed in [v. 2.2.0 ](https://github.com/TinkoffCreditSystems/ng-dompurify/blob/master/CHANGELOG.md#220-2020-03-31)

Thank for using our library!

**Comment by jtammen** [comment]
Hey @MarsiBarsi, 

> Thank for using our library!

awesome, it works now! Thanks for the quick fix!
