### ISSUE TITLE
Routing problem when using hooks

### ISSUE THREAD

**Issue by Olyster** [TinkoffCreditSystems/ng-dompurify#40]
Hi,

I recently tried using hooks in app.module but it creates a collateral effect : the routing isn't working anymore ! Weird problem. The hooks is working and the link is not sanitized but as soon as I add this in app.module provider section : 

{ provide: DOMPURIFY_HOOKS,
      useValue: [
          {
              name: 'uponSanitizeAttribute',
              hook: (node: Element, hookEvt ) => {
                if (hookEvt.attrValue.startsWith('functionName('))
                  hookEvt.forceKeepAttr=true;
              },
          }
      ]
    }

I get Error in promise Cannot find module ... If I remove those lines, routing works fine.

Thanks

**Comment by MarsiBarsi** [comment]
Hi, @Olyster ! 
Thank you for your report. We will fix it soon

**Comment by Olyster** [comment]
Hi there,

I found a solution to the routing problem.

In routing module, instead of using :

loadChildren: './pages/info/info.module#InfoPageModule' and get Cannot find module, import the module and use this syntax : 

loadChildren: () => InfoPageModule

**Comment by Olyster** [comment]
Hi there,

I found a solution to the routing problem.

In routing module, instead of using :

loadChildren: './pages/info/info.module#InfoPageModule' and get Cannot find module error, import the module and use this syntax :

loadChildren: () => InfoPageModule
