### ISSUE TITLE
not compatible with Angular Ivy

### ISSUE THREAD

**Issue by SharimNaveed** [TinkoffCreditSystems/ng-dompurify#54]
i have created a project in angular 9 , and added @tinkoff/ng-dompurify and its peer dependencies. when i import it in my app.module.ts  i am getting error:
    ERROR in node_modules/@tinkoff/ng-dompurify/lib/ng-dompurify.module.d.ts:1:22 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class.

    This likely means that the library (@tinkoff/ng-dompurify) which declares NgDompurifyModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

    1 export declare class NgDompurifyModule {
                           ~~~~~~~~~~~~~~~~~

**Comment by MarsiBarsi** [comment]
Hi! Thank you for your issue

I tried to check our demo on Stackblitz and it works with Ivy correctly:
https://stackblitz.com/edit/angular-ivy-dompurify?file=src%2Fapp%2Fapp.module.ts

Could you please make a stackblitz with your case? 

And did you try removing _package-lock.json_ and _node_modules_ folder, making `npm i` after it?

**Comment by SharimNaveed** [comment]
Thanks @MarsiBarsi  for quick help,
it worked after i removed node_moudles and package-lock.json and then npm i.
