### ISSUE TITLE
Possible Documentation Update

### ISSUE THREAD

**Issue by cpdjh02** [TinkoffCreditSystems/ng-dompurify#55]
I ran into an issue when using the Ivy compiler that was causing the dompurifer not to work if the sanitized html has embeded styles. 

I posted this bug ticket on the angular site:
https://github.com/angular/angular/issues/36794

And was provided with the solution to change from using DomSanitizer to use Sanitizer instead:

```
@NgModule({
    // ...
    providers: [
        {
            provide: DomSanitizer,
            useClass: NgDompurifyDomSanitizer,
        },
    ],
    // ...
})
```

to be 

```
@NgModule({
    // ...
    providers: [
        {
            provide: Sanitizer,
            useClass: NgDompurifyDomSanitizer,
        },
    ],
    // ...
})
```

I'm not sure if there are any features in the ng-dompurify code that this will break but its working for me so I thought, maybe the documentation for ng-dompurify may need to be updated to match.

**Comment by MarsiBarsi** [comment]
Hi, thank you for this issue!
Providing a Sanitizer was not allowed before Ivy, we'll check it better and maybe we'll update our library

**Comment by waterplea** [comment]
Hi @cpdjh02. Looks like this is indeed the way to go, but you do not need `NgDompurifyDomSanitizer`, just use `NgDompurifySanitizer`. Apparently Dom implementation is unnecessary and we might drop it entirely and release a next major version with a smaller bundle. Thank you for bringing this to our attention.

**Comment by cpdjh02** [comment]
Very cool.  Thank you for taking this on so quick!!

**Comment by MarsiBarsi** [comment]
Hi! We made v3.0 that works with Sanitizer and it is 1.5kb less than v2.0 👍  (now our package is 1kb size min + gzipped)
Thank you!
