### ISSUE TITLE
Describe advantages in readme

### ISSUE THREAD

**Issue by zy2ba** [TinkoffCreditSystems/ng-dompurify#68]
Readme tells about easy drop-in replacement angular sanitizer by this package. But readme doesn't suggest - have I any reasons or cases to do this switch? If I already implements my functionality with default sanitizer? If I starts new project? Any other cases? Please add some useful info for easy decision make: use this lib or not?

**Comment by MarsiBarsi** [comment]
Hey! Thanks for your interest in our library :)

This is a good idea, we'll make it someday. Now I can add there a link to an article explaining these all: https://medium.com/angular-in-depth/warning-sanitizing-html-stripped-some-content-and-how-to-deal-with-it-properly-10ff77012d5a
